<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bot (1)</name>
   <tag></tag>
   <elementGuidId>5fe6fc63-f896-4dac-b6ab-678ed9c929ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.footer_robot</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page_wrapper']/footer/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>558eb776-e305-4ecf-96c0-7f6b38de0c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Swag Bot Footer</value>
      <webElementGuid>7b954efc-619d-48d1-9c89-ce1a11b3ee65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer_robot</value>
      <webElementGuid>088731e6-69e1-49d0-98dd-4938aa2370ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/SwagBot_Footer_graphic.2e87acec.png</value>
      <webElementGuid>9bab177c-aad9-4236-8a4a-c39c939b9717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page_wrapper&quot;)/footer[@class=&quot;footer&quot;]/img[@class=&quot;footer_robot&quot;]</value>
      <webElementGuid>ea555cab-0f58-4dde-8509-7eb9c1bc1cfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page_wrapper']/footer/img</value>
      <webElementGuid>19f6404f-6f97-4271-9d4f-545c15b47532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Swag Bot Footer']</value>
      <webElementGuid>07486b24-f31f-4aaf-a787-5e393712c041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/img</value>
      <webElementGuid>38867b65-c795-4090-aeae-3ddcc83e1cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Swag Bot Footer' and @src = '/static/media/SwagBot_Footer_graphic.2e87acec.png']</value>
      <webElementGuid>195d3074-414b-40a3-b816-62705d4da0fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
