<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bot</name>
   <tag></tag>
   <elementGuidId>4cceb65e-6c7b-4c2b-a5c8-0376fb26fd21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.pony_express</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout_complete_container']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ae4c1526-743d-4b9f-b2fe-ae79d4382934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pony Express</value>
      <webElementGuid>b5415a83-7629-492f-be50-de14bf944c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pony_express</value>
      <webElementGuid>4223365b-2b7a-4c5a-8710-910275b02131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/pony-express.46394a5d.png</value>
      <webElementGuid>4ba008b0-a7c8-4846-8a12-75de54f0d64f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout_complete_container&quot;)/img[@class=&quot;pony_express&quot;]</value>
      <webElementGuid>5909e193-afef-4408-82f1-5ea025b18fe0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout_complete_container']/img</value>
      <webElementGuid>9e0e50b9-fbab-45cb-b360-c5969b071be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Pony Express']</value>
      <webElementGuid>3e96ade7-7803-4d3e-89be-28a07aa42610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>e71493e6-621f-479d-a4de-5fe567baf046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Pony Express' and @src = '/static/media/pony-express.46394a5d.png']</value>
      <webElementGuid>7ed1f96e-9024-4cb9-ab7a-b0eb044f77d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
